## SET UP PARAMETERS WITH DEFAULTS WHERE APPROPRIATE
setupBase <- list(NOBSERVATIONS = NA,
                  NVARIABLES = NA,
                  DATAFILE = NA,
                  RESPONSEFILE = NA,
                  WEIGHTSFILE = NA,
                  CENSORFILE = NA,
                  modtype = NA,
                  OUTFILE = file.path(tempdir(), "outputModels.txt"),
                  ITEROUT = file.path(tempdir(), "iterout.txt"),
                  SUMMARYFILE = file.path(tempdir(), "modelsummary.txt"),
                  NOISY = 1,
                  NORMSTAND = 1,
                  PSTART = 2,
                  ONEVAR = 1,
                  iters = 100,
                  NBest = 10,
                  pmax = 15,
                  innerAnneal1 = 0.6,
                  innerAnneal2 = 0.8,
                  innerAnneal3 = 1.0,
                  outerAnneal = 0.4,
                  priormeanp = 5.0)
  
